name: 🚀 First Docker Image Push

on:
  workflow_dispatch:

jobs:
  docker-build-push:

    name: 🐳 Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:

      # ==================================
      # Checkout
      # ==================================
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4


      # ==================================
      # Docker Login
      # ==================================
      - name: 🔐 Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # ==================================
      # Docker Metadata
      # ==================================
      - name: 🧾 Image Information
        run: |
          echo "================================"
          echo "🚀 Building Initial Image"
          echo "Image:"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/Flask-Website-service:latest"
          echo "Time:"
          date
          echo "================================"


      # ==================================
      # Build
      # ==================================
      - name: 🐳 Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/Flask-Website-service:latest .


      # ==================================
      # Push
      # ==================================
      - name: 📤 Push Docker Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/Flask-Website-service:latest


      # ==================================
      # Verify
      # ==================================
      - name: ✅ Completed
        run: |
          echo "============================================================="
          echo "✅ Flask-Website-service : Docker Image Successfully Pushed"
          echo "============================================================="